version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: hapi-robots
    versions:
    - 3.2.2
  - dependency-name: handlebars
    versions:
    - 4.7.7
